version: '3.6'
services:
  jslave-common:
    image: jslave-common
    environment:
      MASTER: 'http://jenkins:8080'
      LABELS: 'docker-cli'
      PASSWORD: 'SWARM-SLAVE-PASS80'
      USERNAME: 'jenkins.swarm'
      FSROOT: '/home/jenkins-slave'
      EXECUTORS: '2'
      NAME: 'static-slave-docker-cli'
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
    env_file:
      - ${DJEG_CUSTOM_CONF_DIR}/config.env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
